// Command genoauthclient generates or verifies fbrcm's masked built-in Google
// Desktop OAuth client source.
package main

import (
	"bytes"
	"crypto/rand"
	"errors"
	"flag"
	"fmt"
	"go/format"
	"io"
	"io/fs"
	"os"
	"path/filepath"
	"strings"
)

const (
	clientIDEnvironment     = "FBRCM_GOOGLE_OAUTH_CLIENT_ID"
	clientSecretEnvironment = "FBRCM_GOOGLE_OAUTH_CLIENT_SECRET"
	defaultOutputPath       = "internal/builtinoauth/credentials_generated.go"
)

func main() {
	if err := run(os.Args[1:]); err != nil {
		fmt.Fprintf(os.Stderr, "genoauthclient: %v\n", err)
		os.Exit(1)
	}
}

func run(args []string) error {
	flags := flag.NewFlagSet("genoauthclient", flag.ContinueOnError)
	flags.SetOutput(os.Stderr)
	clean := flags.Bool("clean", false, "remove the generated credential source")
	output := flags.String("output", defaultOutputPath, "generated source path")
	verify := flags.String("verify", "", "file or directory to scan for plaintext credentials")
	if err := flags.Parse(args); err != nil {
		return err
	}
	if flags.NArg() != 0 {
		return fmt.Errorf("unexpected positional arguments")
	}
	if *clean && *verify != "" {
		return fmt.Errorf("-clean and -verify cannot be combined")
	}
	if *clean {
		return removeGeneratedSource(*output)
	}

	clientID, clientSecret, err := credentialsFromEnvironment()
	if err != nil {
		return err
	}
	if *verify != "" {
		return verifyNoPlaintext(*verify, clientID, clientSecret)
	}

	source, err := renderGeneratedSource(rand.Reader, clientID, clientSecret)
	if err != nil {
		return err
	}
	if err := writeGeneratedSource(*output, source); err != nil {
		return err
	}
	if clientID == "" {
		fmt.Fprintf(os.Stderr, "generated OAuth client source without credentials at %s\n", *output)
	} else {
		fmt.Fprintf(os.Stderr, "generated masked OAuth client source at %s\n", *output)
	}
	return nil
}

func credentialsFromEnvironment() (string, string, error) {
	clientID := strings.TrimSpace(os.Getenv(clientIDEnvironment))
	clientSecret := strings.TrimSpace(os.Getenv(clientSecretEnvironment))
	if (clientID == "") != (clientSecret == "") {
		missing := clientIDEnvironment
		if clientID != "" {
			missing = clientSecretEnvironment
		}
		return "", "", fmt.Errorf("%s is empty; configure both OAuth credential variables or neither", missing)
	}
	return clientID, clientSecret, nil
}

func renderGeneratedSource(random io.Reader, clientID, clientSecret string) ([]byte, error) {
	clientIDCiphertext, clientIDMask, err := maskValue(random, []byte(clientID))
	if err != nil {
		return nil, fmt.Errorf("masking client ID: %w", err)
	}
	clientSecretCiphertext, clientSecretMask, err := maskValue(random, []byte(clientSecret))
	if err != nil {
		return nil, fmt.Errorf("masking client secret: %w", err)
	}

	var source strings.Builder
	source.WriteString("// Code generated by cmd/genoauthclient; DO NOT EDIT.\n")
	source.WriteString("//go:build fbrcm_google_auth\n\n")
	source.WriteString("package builtinoauth\n\n")
	writeByteArray(&source, "clientIDCiphertext", clientIDCiphertext)
	writeByteArray(&source, "clientIDMask", clientIDMask)
	writeByteArray(&source, "clientSecretCiphertext", clientSecretCiphertext)
	writeByteArray(&source, "clientSecretMask", clientSecretMask)
	source.WriteString("func Credentials() (clientID, clientSecret string) {\n")
	source.WriteString("\treturn decode(clientIDCiphertext[:], clientIDMask[:]), decode(clientSecretCiphertext[:], clientSecretMask[:])\n")
	source.WriteString("}\n")

	formatted, err := format.Source([]byte(source.String()))
	if err != nil {
		return nil, fmt.Errorf("formatting generated source: %w", err)
	}
	return formatted, nil
}

func maskValue(random io.Reader, plaintext []byte) ([]byte, []byte, error) {
	mask := make([]byte, len(plaintext))
	if _, err := io.ReadFull(random, mask); err != nil {
		return nil, nil, err
	}
	ciphertext := make([]byte, len(plaintext))
	for index := range plaintext {
		ciphertext[index] = plaintext[index] ^ mask[index]
	}
	return ciphertext, mask, nil
}

func writeByteArray(destination *strings.Builder, name string, values []byte) {
	fmt.Fprintf(destination, "var %s = [...]byte{\n", name)
	for index, value := range values {
		if index%12 == 0 {
			destination.WriteString("\t")
		}
		fmt.Fprintf(destination, "0x%02x,", value)
		if index%12 == 11 || index == len(values)-1 {
			destination.WriteString("\n")
		} else {
			destination.WriteString(" ")
		}
	}
	destination.WriteString("}\n\n")
}

func writeGeneratedSource(path string, source []byte) error {
	directory := filepath.Dir(path)
	if err := os.MkdirAll(directory, 0o755); err != nil {
		return fmt.Errorf("creating generated source directory: %w", err)
	}
	temporary, err := os.CreateTemp(directory, ".credentials-generated-*.go")
	if err != nil {
		return fmt.Errorf("creating temporary generated source: %w", err)
	}
	temporaryPath := temporary.Name()
	defer func() { _ = os.Remove(temporaryPath) }()
	if err := temporary.Chmod(0o600); err != nil {
		_ = temporary.Close()
		return fmt.Errorf("restricting generated source permissions: %w", err)
	}
	if _, err := temporary.Write(source); err != nil {
		_ = temporary.Close()
		return fmt.Errorf("writing generated source: %w", err)
	}
	if err := temporary.Close(); err != nil {
		return fmt.Errorf("closing generated source: %w", err)
	}
	if err := os.Rename(temporaryPath, path); err != nil {
		// Windows does not replace an existing destination atomically. The
		// destination is a disposable generated file, so remove only that exact
		// path and retry.
		if removeErr := os.Remove(path); removeErr != nil && !errors.Is(removeErr, os.ErrNotExist) {
			return fmt.Errorf("replacing generated source: %w", removeErr)
		}
		if renameErr := os.Rename(temporaryPath, path); renameErr != nil {
			return fmt.Errorf("installing generated source: %w", renameErr)
		}
	}
	return nil
}

func removeGeneratedSource(path string) error {
	err := os.Remove(path)
	if err == nil || errors.Is(err, os.ErrNotExist) {
		return nil
	}
	return fmt.Errorf("removing generated source: %w", err)
}

func verifyNoPlaintext(path, clientID, clientSecret string) error {
	inspected := 0
	err := filepath.WalkDir(path, func(candidate string, entry fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if entry.IsDir() || entry.Type()&os.ModeSymlink != 0 {
			return nil
		}
		content, err := os.ReadFile(candidate)
		if err != nil {
			return fmt.Errorf("reading %s: %w", candidate, err)
		}
		inspected++
		for _, credential := range []struct {
			name  string
			value string
		}{
			{name: "client ID", value: clientID},
			{name: "client secret", value: clientSecret},
		} {
			if credential.value == "" {
				continue
			}
			if bytes.Contains(content, []byte(credential.value)) {
				return fmt.Errorf("%s contains the plaintext OAuth %s", candidate, credential.name)
			}
		}
		return nil
	})
	if err != nil {
		return err
	}
	if inspected == 0 {
		return fmt.Errorf("no files found at %s", path)
	}
	fmt.Fprintf(os.Stderr, "verified %d files without plaintext OAuth credentials\n", inspected)
	return nil
}
