package config

// DefaultKeyMap returns complete default TUI keybindings.
func DefaultKeyMap() KeyMap {
	return KeyMap{
		BlockGlobal: {
			ActionQuit:            {"q"},
			ActionForceQuit:       {"ctrl+c"},
			ActionHelp:            {"?"},
			ActionAccounts:        {"ctrl+a"},
			ActionProfiles:        {"ctrl+p"},
			ActionFocusProjects:   {"1"},
			ActionFocusParameters: {"2"},
			ActionFocusConditions: {"3"},
			ActionFocusHistory:    {"4"},
			ActionFocusPromote:    {"9"},
			ActionFocusDetails:    {"5"},
			ActionFocusLogs:       {"0"},
			ActionFocusNext:       {"tab"},
		},
		BlockHelp: {
			ActionCancel:   {"esc"},
			ActionSubmit:   {"enter"},
			ActionUp:       {"up", "ctrl+k"},
			ActionDown:     {"down", "ctrl+j"},
			ActionPageUp:   {"pgup"},
			ActionPageDown: {"pgdown"},
			ActionHome:     {"home"},
			ActionEnd:      {"end"},
		},
		BlockFilter: {
			ActionFilterFuzzy:      {"~"},
			ActionFilterStartsWith: {"^"},
			ActionFilterIncludes:   {"/"},
			ActionFilterExact:      {"="},
			ActionFilterExpression: {":"},
			ActionFilterApply:      {"enter"},
			ActionFilterCancel:     {"esc"},
			ActionFilterUp:         {"up"},
			ActionFilterDown:       {"down"},
		},
		BlockProjects: {
			ActionToggleMode: {"c"},
			ActionRefresh:    {"u"},
			ActionDelete:     {"x"},
			ActionSelect:     {"enter"},
			ActionOpen:       {"o"},
			ActionMark:       {"space"},
			ActionBindAuth:   {"b"},
			ActionImport:     {"i"},
			ActionExport:     {"e"},
			ActionDefaults:   {"d"},
			ActionPromote:    {"v"},
			ActionUp:         {"up", "k"},
			ActionDown:       {"down", "j"},
			ActionPageUp:     {"pgup", "h"},
			ActionPageDown:   {"pgdown", "l"},
			ActionHome:       {"home"},
			ActionEnd:        {"end"},
		},
		BlockPromote: {
			ActionClose:      {"esc"},
			ActionToggle:     {"space"},
			ActionSelectAll:  {"a"},
			ActionSelectNone: {"n"},
			ActionSwap:       {"s"},
			ActionPrune:      {"x"},
			ActionSaveDraft:  {"d"},
			ActionSource:     {"u"},
			ActionPublish:    {"p"},
			ActionUp:         {"up", "k"},
			ActionDown:       {"down", "j"},
			ActionPageUp:     {"pgup"},
			ActionPageDown:   {"pgdown"},
			ActionHome:       {"home"},
			ActionEnd:        {"end"},
			ActionSubmit:     {"enter"},
		},
		BlockParameters: {
			ActionToggleMaximize: {"z"},
			ActionRename:         {"r"},
			ActionEdit:           {"e"},
			ActionNew:            {"a"},
			ActionNewGroup:       {"A"},
			ActionDuplicate:      {"c"},
			ActionMove:           {"m"},
			ActionToggle:         {" ", "space"},
			ActionDelete:         {"x"},
			ActionPublish:        {"p"},
			ActionPublishAll:     {"P"},
			ActionDiscard:        {"d"},
			ActionDiscardAll:     {"D"},
			ActionReload:         {"u"},
			ActionReloadAll:      {"U"},
			ActionCopyName:       {"y"},
			ActionCopyPath:       {"Y"},
			ActionOpenDetails:    {"enter"},
			ActionExpand:         {"right", "l"},
			ActionCollapse:       {"left", "h"},
			ActionExpandAll:      {">"},
			ActionCollapseAll:    {"<"},
			ActionExpandGroups:   {")"},
			ActionCollapseGroups: {"("},
			ActionNextGroup:      {"pgdown"},
			ActionPrevGroup:      {"pgup"},
			ActionFirst:          {"home"},
			ActionLast:           {"end"},
			ActionUp:             {"up", "k"},
			ActionDown:           {"down", "j"},
		},
		BlockConditions: {
			ActionRename:      {"r"},
			ActionEdit:        {"e"},
			ActionColor:       {"c"},
			ActionNew:         {"a"},
			ActionMove:        {"m"},
			ActionDelete:      {"x"},
			ActionPublish:     {"p"},
			ActionPublishAll:  {"P"},
			ActionDiscard:     {"d"},
			ActionDiscardAll:  {"D"},
			ActionCopyName:    {"y"},
			ActionCopyPath:    {"Y"},
			ActionOpenDetails: {"enter"},
			ActionFirst:       {"home"},
			ActionLast:        {"end"},
			ActionUp:          {"up", "k"},
			ActionDown:        {"down", "j"},
			ActionPageUp:      {"pgup", "h"},
			ActionPageDown:    {"pgdown", "l"},
		},
		BlockHistory: {
			ActionHistoryBothOlder: {","}, ActionHistoryBothNewer: {"."},
			ActionHistoryChoose:  {"v"},
			ActionHistoryChanges: {"c"},
			ActionSubmit:         {"enter"},
		},
		BlockHistoryPicker: {
			ActionCancel:           {"esc"},
			ActionToggle:           {"tab", "shift+tab"},
			ActionLeft:             {"left"},
			ActionRight:            {"right"},
			ActionHistoryBothOlder: {","},
			ActionHistoryBothNewer: {"."},
			ActionHistoryRollback:  {"R"},
			ActionReset:            {"r"},
			ActionUp:               {"up", "k"},
			ActionDown:             {"down", "j"},
			ActionPageUp:           {"pgup"},
			ActionPageDown:         {"pgdown"},
			ActionHome:             {"home"},
			ActionEnd:              {"end"},
			ActionSubmit:           {"enter"},
		},
		BlockDetails: {
			ActionClose:     {"esc"},
			ActionNew:       {"a"},
			ActionSubmit:    {"ctrl+enter"},
			ActionEditValue: {"right", "e"},
			ActionColor:     {"c"},
			ActionMove:      {"m"},
			ActionRename:    {"r"},
			ActionCopyName:  {"y"},
			ActionCopyPath:  {"Y"},
			ActionCopyValue: {"ctrl+y"},
			ActionDelete:    {"x"},
		},
		BlockDetailsForm: {
			ActionClose:    {"esc"},
			ActionUp:       {"up", "k"},
			ActionDown:     {"down", "j"},
			ActionPageUp:   {"pgup", "h"},
			ActionPageDown: {"pgdown", "l"},
			ActionHome:     {"home"},
			ActionEnd:      {"end"},
			ActionRight:    {"right"},
			ActionSubmit:   {"enter"},
		},
		BlockLogs: {
			ActionToggleMode:   {"c"},
			ActionLevelDown:    {"["},
			ActionLevelUp:      {"]"},
			ActionResizeGrow:   {"=", "+"},
			ActionResizeShrink: {"-", "_"},
			ActionBlankLine:    {"enter"},
			ActionUp:           {"up", "k"},
			ActionDown:         {"down", "j"},
			ActionPageUp:       {"pgup", "h"},
			ActionPageDown:     {"pgdown", "l"},
			ActionHome:         {"home"},
			ActionEnd:          {"end"},
		},
		BlockDialog: {
			ActionCancel:   {"esc"},
			ActionPrev:     {"left", "h", "shift+tab"},
			ActionNext:     {"right", "l", "tab"},
			ActionUp:       {"up", "k"},
			ActionDown:     {"down", "j"},
			ActionPageUp:   {"pgup"},
			ActionPageDown: {"pgdown"},
			ActionHome:     {"home"},
			ActionEnd:      {"end"},
			ActionSubmit:   {"enter"},
		},
		BlockBoolInput: {
			ActionCancel:    {"esc"},
			ActionCopyValue: {"ctrl+y"},
			ActionSubmit:    {"enter"},
			ActionUp:        {"up", "k"},
			ActionDown:      {"down", "j"},
		},
		BlockDiffView: {
			ActionClose:    {"esc"},
			ActionToggle:   {"space", "enter"},
			ActionUp:       {"up", "k"},
			ActionDown:     {"down", "j"},
			ActionPageUp:   {"pgup"},
			ActionPageDown: {"pgdown"},
			ActionHome:     {"home"},
			ActionEnd:      {"end"},
			ActionLeft:     {"left", "h"},
			ActionRight:    {"right", "l"},
		},
		BlockJSONInput: {
			ActionCancel:    {"esc"},
			ActionCopyValue: {"ctrl+y"},
			ActionFormat:    {"ctrl+f"},
			ActionSave:      {"ctrl+s", "ctrl+enter"},
		},
		BlockNumberInput: {
			ActionCancel:    {"esc"},
			ActionCopyValue: {"ctrl+y"},
			ActionSubmit:    {"enter"},
		},
		BlockStringInput: {
			ActionCancel:         {"esc"},
			ActionCopyValue:      {"ctrl+y"},
			ActionToggleExpanded: {"ctrl+e"},
			ActionSave:           {"ctrl+s", "ctrl+enter"},
			ActionSubmit:         {"enter"},
		},
		BlockMoveInput: {
			ActionCancel: {"esc"},
			ActionSubmit: {"enter"},
			ActionUp:     {"up", "k"},
			ActionDown:   {"down", "j"},
		},
		BlockAuthPicker: {
			ActionCancel: {"esc"},
			ActionSubmit: {"enter"},
			ActionPrev:   {"left", "h", "shift+tab"},
			ActionNext:   {"right", "l", "tab"},
			ActionUp:     {"up", "k"},
			ActionDown:   {"down", "j"},
		},
		BlockAccounts: {
			ActionCancel: {"esc"},
			ActionSubmit: {"enter"},
			ActionDelete: {"x"},
			ActionUp:     {"up", "k"},
			ActionDown:   {"down", "j"},
		},
		BlockProfiles: {
			ActionCancel: {"esc"},
			ActionSubmit: {"enter"},
			ActionRename: {"r"},
			ActionDelete: {"x"},
			ActionUp:     {"up", "k"},
			ActionDown:   {"down", "j"},
		},
		BlockRenameInput: {
			ActionCancel: {"esc"},
			ActionSubmit: {"enter"},
		},
	}
}
